services:
  ########## business services ##########
  duties-service:
    build: ./duties-service
    container_name: duties-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://duties-db/duty_db
      SPRING_DATASOURCE_USERNAME: duty_user
      SPRING_DATASOURCE_PASSWORD: duty_pass
    healthcheck:
      test: curl -f http://duties-service/actuator/health || exit 1
      timeout: 10s
      interval: 7s
      retries: 10
    ports:
      - "7070:7070"
    depends_on:
      - duties-db
    restart: on-failure

  notifications-service:
    build: ./notifications-service
    container_name: notifications-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://notifications-db/notification_db
      SPRING_DATASOURCE_USERNAME: notification_user
      SPRING_DATASOURCE_PASSWORD: notification_pass
    healthcheck:
      test: curl -f http://notifications-service/actuator/health || exit 1
      timeout: 10s
      interval: 7s
      retries: 10
    ports:
      - "8080:8080"
    depends_on:
      - notifications-db
      - profiles-service
    restart: on-failure

  profiles-service:
    build: ./profiles-service
    container_name: profiles-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://profiles-db/profile_db
      SPRING_DATASOURCE_USERNAME: profile_user
      SPRING_DATASOURCE_PASSWORD: profile_pass
    healthcheck:
      test: curl -f http://profiles-service/actuator/health || exit 1
      timeout: 10s
      interval: 7s
      retries: 10
    ports:
      - "9090:9090"
    depends_on:
      - profiles-db
    restart: on-failure

  ########## DB services ##########
  duties-db:
    image: postgres:16.1
    container_name: duties-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=duty_pass
      - POSTGRES_USER=duty_user
      - POSTGRES_DB=duty_db
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 10s
      interval: 7s
      retries: 10
    restart: on-failure

  notifications-db:
    image: postgres:16.1
    container_name: notifications-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=notification_pass
      - POSTGRES_USER=notification_user
      - POSTGRES_DB=notification_db
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 10s
      interval: 7s
      retries: 10
    restart: on-failure

  profiles-db:
    image: postgres:16.1
    container_name: profiles-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_PASSWORD=profile_pass
      - POSTGRES_USER=profile_user
      - POSTGRES_DB=profile_db
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 10s
      interval: 7s
      retries: 10
    restart: on-failure