services:
  ########## business services ##########
  duties:
    build: duties-service
    image: duties-service
    container_name: duties-service
    ports:
      - "7070:7070"
    depends_on:
      - duties-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:6541/duties_db
      - SPRING_DATASOURCE_USERNAME=duties_user
      - SPRING_DATASOURCE_PASSWORD=duties_pass

  notifications:
    build: notifications
    image: notifications
    container_name: notifications
    ports:
      - "8080:8080"
    depends_on:
      - notifications-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:6542/notifications_db
      - SPRING_DATASOURCE_USERNAME=notifications_user
      - SPRING_DATASOURCE_PASSWORD=notifications_pass

  profiles:
    build: profiles
    image: profiles
    container_name: profiles
    ports:
      - "9090:9090"
    depends_on:
      - profiles-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:6542/profiles_db
      - SPRING_DATASOURCE_USERNAME=profiles_user
      - SPRING_DATASOURCE_PASSWORD=profiles_pass

  ########## DB services ##########
  duties-db:
    image: postgres:16.1
    container_name: duties-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=duties_pass
      - POSTGRES_USER=duties_user
      - POSTGRES_DB=duties_db
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  notifications-db:
    image: postgres:16.1
    container_name: notifications-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=notifications_pass
      - POSTGRES_USER=notifications_user
      - POSTGRES_DB=notifications_db
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  profiles-db:
    image: postgres:16.1
    container_name: profiles-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_PASSWORD=profiles_pass
      - POSTGRES_USER=profiles_user
      - POSTGRES_DB=profiles_db
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10