openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:7070
  description: Generated server url
paths:
  /users:
    get:
      tags:
      - user-controller
      operationId: getUserIdsByName
      parameters:
      - name: name
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  type: integer
                  format: int64
    put:
      tags:
      - user-controller
      operationId: put
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: integer
                format: int64
    post:
      tags:
      - user-controller
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewUserRequest"
        required: true
      responses:
        "201":
          description: Created
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserDto"
  /duties:
    put:
      tags:
      - duty-controller
      operationId: updateDuty
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateDutyRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Duty"
    post:
      tags:
      - duty-controller
      operationId: createDuty
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateDutyRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Duty"
  /users/{id}:
    get:
      tags:
      - user-controller
      operationId: getUserById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserFullInfoDto"
  /users/usersIds:
    get:
      tags:
      - user-controller
      operationId: getUserIdsByUsernameAndPassword
      parameters:
      - name: name
        in: query
        required: true
        schema:
          type: string
      - name: password
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  type: integer
                  format: int64
  /users/notexisting:
    get:
      tags:
      - user-controller
      operationId: getNotExistingUsersByIds
      parameters:
      - name: ids
        in: query
        required: true
        schema:
          type: array
          items:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  type: integer
                  format: int64
  /users/info:
    get:
      tags:
      - user-controller
      operationId: getUsersByIds
      parameters:
      - name: ids
        in: query
        required: true
        schema:
          type: array
          items:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserDtoPartial"
  /duties/{dutyId}:
    get:
      tags:
      - duty-controller
      operationId: getDuty
      parameters:
      - name: dutyId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Duty"
    delete:
      tags:
      - duty-controller
      operationId: deleteDuty
      parameters:
      - name: dutyId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "204":
          description: No Content
  /duties/user/{userId}:
    get:
      tags:
      - duty-controller
      operationId: getUserDuty
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserDutyDto"
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        password:
          type: string
        organization:
          type: string
        avatar:
          type: integer
          format: int32
        about:
          type: string
    UpdateDutyRequest:
      required:
      - id
      type: object
      properties:
        id:
          type: integer
          format: int64
        start_time:
          type: string
          format: date-time
        interval:
          type: object
          properties:
            seconds:
              type: integer
              format: int64
            zero:
              type: boolean
            nano:
              type: integer
              format: int32
            negative:
              type: boolean
            positive:
              type: boolean
            units:
              type: array
              items:
                type: object
                properties:
                  durationEstimated:
                    type: boolean
                  timeBased:
                    type: boolean
                  dateBased:
                    type: boolean
        ids:
          type: array
          items:
            type: integer
            format: int64
    Duty:
      type: object
      properties:
        id:
          type: integer
          format: int64
        start_time:
          type: string
          format: date-time
        interval:
          type: object
          properties:
            seconds:
              type: integer
              format: int64
            zero:
              type: boolean
            nano:
              type: integer
              format: int32
            negative:
              type: boolean
            positive:
              type: boolean
            units:
              type: array
              items:
                type: object
                properties:
                  durationEstimated:
                    type: boolean
                  timeBased:
                    type: boolean
                  dateBased:
                    type: boolean
        ids:
          type: array
          items:
            type: integer
            format: int64
    NewUserRequest:
      required:
      - email
      - name
      - password
      - phone
      type: object
      properties:
        name:
          maxLength: 250
          minLength: 2
          type: string
        email:
          maxLength: 100
          minLength: 6
          type: string
        phone:
          type: string
        password:
          maxLength: 40
          minLength: 8
          type: string
    UserDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        phone:
          type: string
    CreateDutyRequest:
      required:
      - ids
      - interval
      - start_time
      type: object
      properties:
        start_time:
          type: string
          format: date-time
        interval:
          type: object
          properties:
            seconds:
              type: integer
              format: int64
            zero:
              type: boolean
            nano:
              type: integer
              format: int32
            negative:
              type: boolean
            positive:
              type: boolean
            units:
              type: array
              items:
                type: object
                properties:
                  durationEstimated:
                    type: boolean
                  duration:
                    type: object
                    properties:
                      seconds:
                        type: integer
                        format: int64
                      zero:
                        type: boolean
                      nano:
                        type: integer
                        format: int32
                      negative:
                        type: boolean
                      positive:
                        type: boolean
                  timeBased:
                    type: boolean
                  dateBased:
                    type: boolean
        ids:
          type: array
          items:
            type: integer
            format: int64
    UserFullInfoDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        organization:
          type: string
        avatar:
          type: integer
          format: int32
        about:
          type: string
    UserDtoPartial:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        avatar:
          type: integer
          format: int32
    UserDutyDto:
      type: object
      properties:
        nextDutyDate:
          type: string
          format: date-time
        duration:
          type: object
          properties:
            seconds:
              type: integer
              format: int64
            zero:
              type: boolean
            nano:
              type: integer
              format: int32
            negative:
              type: boolean
            positive:
              type: boolean
            units:
              type: array
              items:
                type: object
                properties:
                  durationEstimated:
                    type: boolean
                  timeBased:
                    type: boolean
                  dateBased:
                    type: boolean
        intervalBetweenDuties:
          type: object
          properties:
            seconds:
              type: integer
              format: int64
            zero:
              type: boolean
            nano:
              type: integer
              format: int32
            negative:
              type: boolean
            positive:
              type: boolean
            units:
              type: array
              items:
                type: object
                properties:
                  durationEstimated:
                    type: boolean
                  timeBased:
                    type: boolean
                  dateBased:
                    type: boolean
