openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:7070
  description: Generated server url
paths:
  /duties:
    put:
      tags:
      - duty-controller
      operationId: updateDuty
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateDutyRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Duty"
    post:
      tags:
      - duty-controller
      operationId: createDuty
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateDutyRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Duty"
  /duties/{dutyId}:
    get:
      tags:
      - duty-controller
      operationId: getDuty
      parameters:
      - name: dutyId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Duty"
    delete:
      tags:
      - duty-controller
      operationId: deleteDuty
      parameters:
      - name: dutyId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "204":
          description: No Content
  /duties/user/{userId}:
    get:
      tags:
      - duty-controller
      operationId: getUserDuty
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserDutyDto"
components:
  schemas:
    UpdateDutyRequest:
      required:
      - id
      type: object
      properties:
        id:
          type: integer
          format: int64
        start_time:
          type: string
          format: date-time
        interval:
          type: object
          properties:
            seconds:
              type: integer
              format: int64
            zero:
              type: boolean
            nano:
              type: integer
              format: int32
            negative:
              type: boolean
            positive:
              type: boolean
            units:
              type: array
              items:
                type: object
                properties:
                  durationEstimated:
                    type: boolean
                  timeBased:
                    type: boolean
                  dateBased:
                    type: boolean
        ids:
          type: array
          items:
            type: integer
            format: int64
    Duty:
      type: object
      properties:
        id:
          type: integer
          format: int64
        start_time:
          type: string
          format: date-time
        interval:
          type: object
          properties:
            seconds:
              type: integer
              format: int64
            zero:
              type: boolean
            nano:
              type: integer
              format: int32
            negative:
              type: boolean
            positive:
              type: boolean
            units:
              type: array
              items:
                type: object
                properties:
                  durationEstimated:
                    type: boolean
                  timeBased:
                    type: boolean
                  dateBased:
                    type: boolean
        ids:
          type: array
          items:
            type: integer
            format: int64
    CreateDutyRequest:
      required:
      - ids
      - interval
      - start_time
      type: object
      properties:
        start_time:
          type: string
          format: date-time
        interval:
          type: object
          properties:
            seconds:
              type: integer
              format: int64
            zero:
              type: boolean
            nano:
              type: integer
              format: int32
            negative:
              type: boolean
            positive:
              type: boolean
            units:
              type: array
              items:
                type: object
                properties:
                  durationEstimated:
                    type: boolean
                  duration:
                    type: object
                    properties:
                      seconds:
                        type: integer
                        format: int64
                      zero:
                        type: boolean
                      nano:
                        type: integer
                        format: int32
                      negative:
                        type: boolean
                      positive:
                        type: boolean
                  timeBased:
                    type: boolean
                  dateBased:
                    type: boolean
        ids:
          type: array
          items:
            type: integer
            format: int64
    UserDutyDto:
      type: object
      properties:
        nextDutyDate:
          type: string
          format: date-time
        duration:
          type: object
          properties:
            seconds:
              type: integer
              format: int64
            zero:
              type: boolean
            nano:
              type: integer
              format: int32
            negative:
              type: boolean
            positive:
              type: boolean
            units:
              type: array
              items:
                type: object
                properties:
                  durationEstimated:
                    type: boolean
                  timeBased:
                    type: boolean
                  dateBased:
                    type: boolean
        intervalBetweenDuties:
          type: object
          properties:
            seconds:
              type: integer
              format: int64
            zero:
              type: boolean
            nano:
              type: integer
              format: int32
            negative:
              type: boolean
            positive:
              type: boolean
            units:
              type: array
              items:
                type: object
                properties:
                  durationEstimated:
                    type: boolean
                  timeBased:
                    type: boolean
                  dateBased:
                    type: boolean
