openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /notifications:
    put:
      tags:
      - notifications-controller
      operationId: updateNotification
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateNotificationRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Notification"
    post:
      tags:
      - notifications-controller
      operationId: createNotification
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateNotificationRequest"
        required: true
      responses:
        "201":
          description: Created
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Notification"
  /notifications/{notificationIds}:
    get:
      tags:
      - notifications-controller
      operationId: getNotificationsFullData
      parameters:
      - name: notificationIds
        in: path
        required: true
        schema:
          type: array
          items:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Notification"
  /notifications/{notificationId}:
    delete:
      tags:
      - notifications-controller
      operationId: deleteNotification
      parameters:
      - name: notificationId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "204":
          description: No Content
  /notifications/array/{notificationIds}:
    delete:
      tags:
      - notifications-controller
      operationId: deleteNotifications
      parameters:
      - name: notificationIds
        in: path
        required: true
        schema:
          type: array
          items:
            type: integer
            format: int64
      responses:
        "204":
          description: No Content
components:
  schemas:
    UpdateNotificationRequest:
      type: object
      properties:
        id:
          type: integer
          format: int64
        type:
          type: string
        content:
          type: string
        time_to_show:
          type: string
        interval_to_repeat:
          type: object
          properties:
            seconds:
              type: integer
              format: int64
            zero:
              type: boolean
            nano:
              type: integer
              format: int32
            negative:
              type: boolean
            positive:
              type: boolean
            units:
              type: array
              items:
                type: object
                properties:
                  durationEstimated:
                    type: boolean
                  timeBased:
                    type: boolean
                  dateBased:
                    type: boolean
        userId:
          type: integer
          format: int64
        immediately:
          type: boolean
    Notification:
      required:
      - content
      - userId
      type: object
      properties:
        id:
          type: integer
          format: int64
        type:
          type: string
        content:
          type: string
        time_to_show:
          type: string
          format: date-time
        interval_to_repeat:
          type: object
          properties:
            seconds:
              type: integer
              format: int64
            zero:
              type: boolean
            nano:
              type: integer
              format: int32
            negative:
              type: boolean
            positive:
              type: boolean
            units:
              type: array
              items:
                type: object
                properties:
                  durationEstimated:
                    type: boolean
                  timeBased:
                    type: boolean
                  dateBased:
                    type: boolean
        userId:
          type: integer
          format: int64
        immediately:
          type: boolean
    CreateNotificationRequest:
      required:
      - content
      - type
      - userId
      type: object
      properties:
        type:
          type: string
        content:
          type: string
        time_to_show:
          type: string
        interval_to_repeat:
          type: object
          properties:
            seconds:
              type: integer
              format: int64
            zero:
              type: boolean
            nano:
              type: integer
              format: int32
            negative:
              type: boolean
            positive:
              type: boolean
            units:
              type: array
              items:
                type: object
                properties:
                  durationEstimated:
                    type: boolean
                  timeBased:
                    type: boolean
                  dateBased:
                    type: boolean
        userId:
          type: integer
          format: int64
        immediately:
          type: boolean
