openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:9090
  description: Generated server url
paths:
  /users:
    get:
      tags:
      - user-controller
      operationId: getUserIdsByName
      parameters:
      - name: name
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  type: integer
                  format: int64
    put:
      tags:
      - user-controller
      operationId: put
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: integer
                format: int64
    post:
      tags:
      - user-controller
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewUserRequest"
        required: true
      responses:
        "201":
          description: Created
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserDto"
  /users/{id}:
    get:
      tags:
      - user-controller
      operationId: getUserById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserFullInfoDto"
  /users/usersIds:
    get:
      tags:
      - user-controller
      operationId: getUserIdsByUsernameAndPassword
      parameters:
      - name: name
        in: query
        required: true
        schema:
          type: string
      - name: password
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  type: integer
                  format: int64
  /users/notexisting:
    get:
      tags:
      - user-controller
      operationId: getNotExistingUsersByIds
      parameters:
      - name: ids
        in: query
        required: true
        schema:
          type: array
          items:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  type: integer
                  format: int64
  /users/info:
    get:
      tags:
      - user-controller
      operationId: getUsersByIds
      parameters:
      - name: ids
        in: query
        required: true
        schema:
          type: array
          items:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserDtoPartial"
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        password:
          type: string
        organization:
          type: string
        avatar:
          type: integer
          format: int32
        about:
          type: string
    NewUserRequest:
      required:
      - email
      - name
      - password
      - phone
      type: object
      properties:
        name:
          maxLength: 250
          minLength: 2
          type: string
        email:
          maxLength: 100
          minLength: 6
          type: string
        phone:
          type: string
        password:
          maxLength: 40
          minLength: 8
          type: string
    UserDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        phone:
          type: string
    UserFullInfoDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        organization:
          type: string
        avatar:
          type: integer
          format: int32
        about:
          type: string
    UserDtoPartial:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        avatar:
          type: integer
          format: int32
