spring:
  application:
    name: profiles-service
  datasource:
    url: jdbc:postgresql://localhost:6543/profile_db
    username: profile_user
    password: profile_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true  # for debug only
  sql:
    init:
      mode: always

server:
  port: 9090
  error:
    include-stacktrace: never

  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health, info
