spring:
  application:
    name: profiles-service
  datasource:
    url: jdbc:postgresql://localhost:6543/profiles_db
    username: profiles_user
    password: profiles_pass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true  # for debug only
  sql:
    init:
      mode: always

server:
  port: 9090
  error:
    include-stacktrace: always

management:
  endpoints:
    web:
      exposure:
        include: health, info