spring:
  application:
    name: profiles-service
  datasource:
    url: jdbc:postgresql://localhost:6541/duties_db
    username: duties_user
    password: duties_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

server:
  port: 7070
  error:
    include-stacktrace: always

management:
  endpoints:
    web:
      exposure:
        include: health, info