spring:
  application:
    name: profiles-service
  datasource:
    url: jdbc:postgresql://localhost:6541/duty_db
    username: duty_user
    password: duty_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

server:
  port: 7070
  error:
    include-stacktrace: never

management:
  endpoints:
    web:
      exposure:
        include: health, info

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html


users:
  url: http://profiles-service:9090