spring:
  application:
    name: notifications-service
  datasource:
    url: jdbc:postgresql://localhost:6542/notification_db
    username: notification_user
    password: notification_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: argus.treker@gmail.com
    password: INSERT_PASSWORD_HERE
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.springframework.jdbc.datasource.DataSourceUtils: DEBUG

users:
  url: http://profiles-service:9090

server:
  port: 8080
  error:
    include-stacktrace: never

aero-sms:
  email: argus.treker@gmail.com
  key: INSERT_KEY_HERE


management:
  endpoints:
    web:
      exposure:
        include: health, info